from psycopg2 import connect, DatabaseError
from connection_info import connection_info


def create_tables():

    pass
    # try:
    #     conn = connect(**connection_info)
    #     cur = conn.cursor()
    #
    #     for cls in []:
    #         cls.create_table()
    #
    #
